title: María García Psicóloga en Logroño
email: mariagarciafernandez@cop.es
description: >- # this means to ignore newlines until "baseurl:"
   Psicóloga en Logroño y online. Consulta de psicología en Logroño (La Rioja).
   Terapia individual, familiar o de pareja. Problemas de conducta,
   estado de ánimo, ansidedad, depresión, estrés y duelo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mariagarciapsicologa.es/" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - node_modules
  - _webpack
  - tailwind.config.js
  - postcss.config.js
  - webpack.config.js
  - package.json
  - yarn.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
